---
- name: RedHat - Ensure Java is installed
  yum:
    name: "{{ java }}"
    state: "present"
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Debian - Ensure Java is installed
  apt: name={{ java }} state="present"
  when: ansible_os_family == 'Debian'

- name: Check java version
  command: java -version 2>&1 | grep OpenJDK
  register: open_jdk
  changed_when: false
  
- name: refresh the java ca-certificates
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
  when: ansible_distribution == 'Ubuntu' and open_jdk.rc == 0
  changed_when: false